color_list1=set(["white","black","red"])
color_list2=set(["red","green"])
print("the original set of elements are:")
print(color_list1)
print(color_list2)
print("\n Difference of color_list1 and color_list2")
print(color_list1.difference(color_list2))
print("\n Difference of color_list2 and color_list1")
print(color_list2.difference(color_list1))
